### PR TITLE
Call --mode-cmd interactively if it is a command

### PR DESCRIPTION
**Pull request by vapniks**
This allows the user to choose a starting directory which may be necessary for some repls

### CODE REVIEW

**Comment by vapniks** [comment]
Done. Have a look at the changes.

**Comment by tomterl** [comment]
Nice! Thanks a lot.

**Comment by tomterl** [comment]
Melpa picked the change up -- I'll wait a bit for comments from users and tag a stable release in a couple of  days.

**Comment by vapniks** [comment]
great

**Pull request merged**
